# MAE 306 PSET 3

## Jacobi Method

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A_1 = np.array([[4, -1, 0], [-1, 4, -1],[0, -1, 4]])
A_2 = np.array([[-1, 0, 0], [0, -1, 0],[0, 0, -1]])
A_3 = np.array([[0, 0, 0], [0, 0, 0],[0, 0, 0]])

In [3]:
A_r1 = np.hstack((A_1,A_2,A_3))
A_r2 = np.hstack((A_2,A_1,A_2))
A_r3 = np.hstack((A_3,A_2,A_1))

In [4]:
A = np.vstack((A_r1,A_r2,A_r3))

In [5]:
b = np.array([[1],[1],[1],[1],[1],[1],[1],[1],[1]])

In [6]:
D = np.diag(np.diag(A))
D_inv = np.linalg.inv(D)

In [7]:
L = np.tril(A)-D

In [8]:
U = np.triu(A)-D

In [10]:
x_i = np.array([[0],[0],[0],[0],[0],[0],[0],[0],[0]])
diff = 1
count = 0

while abs(diff)>0.001:
    r_1 = np.dot(A,x_i)-b
    x_n1 = -np.dot(np.dot(D_inv,(L+U)),x_i)+np.dot(D_inv,b)
    r_n1 = np.dot(A,x_n1)-b
    diff = np.linalg.norm(r_n1 - r_1)
    x_i = x_n1
    count += 1
    
print(x_i)
print(count)

[[0.68707275]
 [0.87438965]
 [0.68707275]
 [0.87438965]
 [1.12414551]
 [0.87438965]
 [0.68707275]
 [0.87438965]
 [0.68707275]]
21


## Steepest descent method

In [48]:
x_i = np.array([[0],[0],[0],[0],[0],[0],[0],[0],[0]])
diff = np.linalg.norm(np.array([[1],[1],[1],[1],[1],[1],[1],[1],[1]]))
F_current = (1/2)*(np.dot(np.dot(np.transpose(x_i), A), x_i))-(np.dot(np.transpose(b), x_i))

count = 0
while abs(diff) > 0.001:
    r = b - np.dot(A,x_i)
    a = (np.dot(np.transpose(r),r))/(np.dot(np.dot(np.transpose(r),A),r))
    x_i1 = x_i + a*r
    F = (1/2)*(np.dot(np.dot(np.transpose(x_i1), A), x_i1))-(np.dot(np.transpose(b), x_i1))
    diff = F - F_current
    x_i = x_i1
    F_current = F
    count += 1
print(x_i)
print(count)

[[0.6796875]
 [0.859375 ]
 [0.6796875]
 [0.859375 ]
 [1.109375 ]
 [0.859375 ]
 [0.6796875]
 [0.859375 ]
 [0.6796875]]
7


In [11]:
x_i = np.array([[0],[0],[0],[0],[0],[0],[0],[0],[0]])
diff = 1

count = 0
while abs(diff) > 0.001:
    r = b - np.dot(A,x_i)
    x1 = np.dot(A,x_i) - b
    a = (np.dot(np.transpose(r),r))/(np.dot(np.dot(np.transpose(r),A),r))
    x_i1 = x_i + a*r
    x2 = np.dot(A,x_i1) - b
    diff = np.linalg.norm(x1 - x2)
    x_i = x_i1
    x1 = x2
    count += 1
print(x_i)
print(count)

[[0.68743896]
 [0.87487793]
 [0.68743896]
 [0.87487793]
 [1.12487793]
 [0.87487793]
 [0.68743896]
 [0.87487793]
 [0.68743896]]
21


## Conjugate Gradient Method

In [70]:
x_i = np.array([[0],[0],[0],[0],[0],[0],[0],[0],[0]])
r = b - np.dot(A,x_i)
d = r
diff = np.linalg.norm(np.array([[1],[1],[1],[1],[1],[1],[1],[1],[1]]))
count = 0

while abs(diff) > 0.001:
    r = b - np.dot(A,x_i)
    a_i = np.dot(np.transpose(r),r)/np.dot(np.dot(np.transpose(d),A),d)
    x_i1 = x_i + a_i*d
    r_i1 = r - a_i*np.dot(A,d)
    B = np.dot(np.transpose(r_i1),r_i1)/np.dot(np.transpose(r),r)
    d_i1 = r_i1 + B*d
    diff_1 = b - np.dot(A,x_i)
    diff_2 = b - np.dot(A,x_i1)
    diff = np.linalg.norm(diff_1 - diff_2)
    x_i = x_i1
    r = r_i1
    d = d_i1
    count += 1
    
print(x_i)
print(count)

[[0.6875]
 [0.875 ]
 [0.6875]
 [0.875 ]
 [1.125 ]
 [0.875 ]
 [0.6875]
 [0.875 ]
 [0.6875]]
4
