# MAE 306 PROBLEM SET 2

## Creating the steepest descent algorithm

In [3]:
import numpy as np
import matplotlib.pyplot as plt

#### Initialising and creating all the necessary arrays

In [61]:
A = np.array([[2, -1], [-1, 2]])
print(A)
b = np.array([[1], [2]])
xi = np.array([[3], [0]])

[[ 2 -1]
 [-1  2]]


#### Creating the loop

In [62]:
F_current = (1/2)*(np.dot(np.dot(np.transpose(xi), A), xi))-(np.dot(np.transpose(b), xi))
print(F_current)

[[6.]]


In [72]:
diff = 1
count = 0
while abs(diff) > 0.0001:
    r = b - np.dot(A,xi)
    a = (np.dot(np.transpose(r),r))/(np.dot(np.dot(np.transpose(r),A),r))
    x_i1 = xi + a*r
    F = (1/2)*(np.dot(np.dot(np.transpose(x_i1), A), x_i1))-(np.dot(np.transpose(b), x_i1))
    diff = F - F_current
    xi = x_i1
    F_current = F
    count += 1
print(count)
print(xi)

1
[[1.33333333]
 [1.66728164]]


Running with different initial x_i values.

In [70]:
A = np.array([[2, -1], [-1, 2]])
b = np.array([[1], [2]])
xi = np.array([[0], [3]])
F_current = (1/2)*(np.dot(np.dot(np.transpose(xi), A), xi))-(np.dot(np.transpose(b), xi))
diff = 1
count = 0
while abs(diff) > 0.0001:
    r = b - np.dot(A,xi)
    a = (np.dot(np.transpose(r),r))/(np.dot(np.dot(np.transpose(r),A),r))
    x_i1 = xi + a*r
    F = (1/2)*(np.dot(np.dot(np.transpose(x_i1), A), x_i1))-(np.dot(np.transpose(b), x_i1))
    diff = F - F_current
    xi = x_i1
    F_current = F
    count += 1
print(count)
print(xi)

2
[[1.33333333]
 [1.66666667]]


In [71]:
A = np.array([[2, -1], [-1, 2]])
b = np.array([[1], [2]])
xi = np.array([[3], [3]])
F_current = (1/2)*(np.dot(np.dot(np.transpose(xi), A), xi))-(np.dot(np.transpose(b), xi))
diff = 1
count = 0
while abs(diff) > 0.0001:
    r = b - np.dot(A,xi)
    a = (np.dot(np.transpose(r),r))/(np.dot(np.dot(np.transpose(r),A),r))
    x_i1 = xi + a*r
    F = (1/2)*(np.dot(np.dot(np.transpose(x_i1), A), x_i1))-(np.dot(np.transpose(b), x_i1))
    diff = F - F_current
    xi = x_i1
    F_current = F
    count += 1
print(count)
print(xi)

6
[[1.33538326]
 [1.66830661]]


Using the first initial vector (3,0) allows for the minimum of the function to be calculated most rapidly. This is likely indicative of the fact that this vector is closest to the minimum.

## Creating the Newton-Raphson algorithm for multivariate functions

In [182]:
# input initial x array
x_i = np.array([0,0,0])

# define the functions
f1 = ((x_i[0] ** 2)*np.exp(-x_i[1]))+x_i[2]-0.395028
f2 = x_i[0]-2.2002*((x_i[1] ** 2)+(x_i[2] ** 2))
f3 = x_i[0]+x_i[1]-(x_i[2] ** 3)-0.710317

F = np.array([f1, f2, f3])

"""
# determine Jacobian
J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])
print(J)
"""

# give some initial error array
erf = np.array([1,1,1])
erf_norm = np.linalg.norm(erf)

while erf_norm > 0.0001:
    J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])
    x_i1 = x_i - np.dot(np.linalg.inv(J),F)
    erf = x_i1 - x_i
    erf_norm = np.linalg.norm(erf)
    x_i = x_i1
print(x_i)


KeyboardInterrupt: 

Since the above code is not working, I assume there is some 

In [94]:
# input initial x array
x_i = np.array([0,0,0])

# define the functions
f1 = ((x_i[0] ** 2)*np.exp(-x_i[1]))+x_i[2]-0.395028
f2 = x_i[0]-2.2002*((x_i[1] ** 2)+(x_i[2] ** 2))
f3 = x_i[0]+x_i[1]-(x_i[2] ** 2)-0.710317

# define an array for the functions? not sure if necessary
F = np.array([f1, f2, f3])

# determine Jacobian
J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**3)]])

# give some initial error array
erf = np.array([1,1,1])



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [139]:
# input initial x array
x_i = np.array([0,0,0])

# define the functions
f1 = ((x_i[0] ** 2)*np.exp(-x_i[1]))+x_i[2]-0.395028
f2 = (x_i[0]/((x_i[1] ** 2)+(x_i[2] ** 2)))-2.20022
f3 = x_i[0]+x_i[1]-(x_i[2] ** 3)-0.710317

F = np.array([f1, f2, f3])

# determine Jacobian
J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])

# give some initial error array
erf = np.array([1,1,1])
erf_norm = np.linalg.norm(erf)

while erf_norm > 0.0001:
    x_i1 = xi - np.dot(np.linalg.inv(J),F)
    erf = x_i1 - x_i
    erf_norm = np.linalg.norm(erf)
    x_i = x_i1
print(x_i)

[nan nan nan]


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in long_scalars
  


In [170]:
# input initial x array
x_i = np.array([0,0,0])

# define the functions
f1 = ((x_i[0] ** 2)*np.exp(-x_i[1]))+x_i[2]-0.395028
f2 = x_i[0]-2.2*((x_i[1] ** 2)+(x_i[2] ** 2))
f3 = x_i[0]+x_i[1]-(x_i[2] ** 3)-0.710317

F = np.array([f1, f2, f3])

# give some initial error array
erf = np.array([1,1,1])


for i in x_i:
   while abs(erf[i])>0.0001:
        J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])
        x_i1 = x_i - np.dot(np.linalg.inv(J),F)
        erf = x_i1 - x_i
        x_i = x_i1
print(x_i)



[0.       0.710317 0.395028]
[0.       0.710317 0.395028]


In [ ]:
# input initial x array
x_i = np.array([0,0,0])

# define the functions
f1 = ((x_i[0] ** 2)*np.exp(-x_i[1]))+x_i[2]-0.395028
f2 = x_i[0]/((x_i[1] ** 2)+(x_i[2] ** 2))-2.20002
f3 = x_i[0]+x_i[1]-(x_i[2] ** 3)-0.710317

F = np.array([f1, f2, f3])

# give some initial error array
erf = np.array([1,1,1])
erf_norm = np.linalg.norm(erf)

for i in x_i:
   while abs(erf[i])>0.0001:
    J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])
    x_i1 = xi - np.dot(np.linalg.inv(J),F)
    erf = x_i1 - x_i
    x_i = x_i1
print(x_i)

In [181]:
# input initial x array
x_i = np.array([0,0,0])

# define the functions
f1 = ((x_i[0] ** 2)*np.exp(-x_i[1]))+x_i[2]-0.395028
f2 = x_i[0]-2.2*((x_i[1] ** 2)+(x_i[2] ** 2))
f3 = x_i[0]+x_i[1]-(x_i[2] ** 3)-0.710317

F = np.array([f1, f2, f3])

# give some initial error array
erf = np.array([1,1,1])

while (abs(erf[0])>0.0001) & (abs(erf[1])>0.0001) & (abs(erf[2])>0.0001):
    f1 = ((x_i[0] ** 2)*np.exp(-x_i[1]))+x_i[2]-0.395028
    f2 = x_i[0]-2.2*((x_i[1] ** 2)+(x_i[2] ** 2))
    f3 = x_i[0]+x_i[1]-(x_i[2] ** 3)-0.710317
    J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])
    x_i1 = x_i - np.dot(np.linalg.inv(J),F)
    erf = x_i1 - x_i
    print(erf)
    x_i = x_i1
print(x_i)



[0.       0.710317 0.395028]
[0.       0.710317 0.395028]


In [4]:
def F(x_i):
    f1 = ((x_i[0] ** 2)*np.exp(-x_i[1]))+x_i[2]-0.385028
    f2 = x_i[0]-2.2002*((x_i[1] ** 2)+(x_i[2] ** 2))
    f3 = x_i[0]+x_i[1]-(x_i[2] ** 3)-0.710317
    return np.array([f1, f2, f3])

In [5]:
# input initial x array
x_i = np.array([0,0,0])

# define the functions
F_start = F(x_i)

# give some initial error array
erf = np.array([1,1,1])
erf_norm = np.linalg.norm(erf)
count = 0

while abs(erf_norm) > 0.0001:
    J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])
    x_i1 = x_i - np.dot(np.linalg.inv(J),F(x_i))
    F_new = F(x_i1)
    erf = F_start - F_new
    erf_norm = np.linalg.norm(erf)
    F_start = F_new
    x_i = x_i1
    count += 1
print(x_i)
print(count)

[0.39999905 0.33000114 0.27000088]
6


In [200]:
# input initial x array
x_i = np.array([1,1,1])

# define the functions
F_start = F(x_i)

# give some initial error array
erf = np.array([1,1,1])
erf_norm = np.linalg.norm(erf)
count = 0

while abs(erf_norm) > 0.0001:
    J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])
    x_i1 = x_i - np.dot(np.linalg.inv(J),F(x_i))
    F_new = F(x_i1)
    erf = F_start - F_new
    erf_norm = np.linalg.norm(erf)
    F_start = F_new
    x_i = x_i1
    count += 1
print(x_i)
print(count)

[0.40443535 0.32715873 0.27710053]
6


In [203]:
# input initial x array
x_i = np.array([0.5,0.5,0.5])

# define the functions
F_start = F(x_i)

# give some initial error array
erf = np.array([1,1,1])
erf_norm = np.linalg.norm(erf)
count = 0

while abs(erf_norm) > 0.0001:
    J = np.array([[2*x_i[0]*np.exp(-x_i[1]), -(x_i[0]**2)*np.exp(-x_i[1]), 1], [1, -2.200022*2*x_i[1], -2.200022*2*x_i[2]], [1, 1, -3*(x_i[2]**2)]])
    x_i1 = x_i - np.dot(np.linalg.inv(J),F(x_i))
    F_new = F(x_i1)
    erf = F_start - F_new
    erf_norm = np.linalg.norm(erf)
    F_start = F_new
    x_i = x_i1
    count += 1
print(x_i)
print(count)

[0.40443535 0.32715873 0.27710053]
4
